### PR TITLE
Add sass and resources optional configurations to ext-react-webpack generated app.json

### PR DESCRIPTION
**Pull request by scotthovestadt**
See: https://github.com/sencha/ext-react/issues/91

### CODE REVIEW

**Comment by branflake2267** [comment]
Thanks for your contribution. I'll pass it off to the team.

**Comment by branflake2267** [comment]
@mgusmano ^^ Hows this look so far?

**Comment by mgusmano** [comment]
can you fix the merge conflicts?

**Comment by mgusmano** [comment]
webpack plugin is now common, not product specific

**Pull request closed without merging**
